def region(region):
    region = region.lower()
    regions = {
        "jakarta": "Asia/Jakarta",
        "china": "Asia/Shanghai",
        "tokyo": "Asia/Tokyo",
        "new york": "America/New_York",
        "london": "Europe/London",
        "dubai": "Asia/Dubai",
        "sydney": "Australia/Sydney",
        "berlin": "Europe/Berlin",
        "moscow": "Europe/Moscow",
        "paris": "Europe/Paris",
        "los angeles": "America/Los_Angeles",
        "toronto": "America/Toronto",
        "mexico city": "America/Mexico_City",
        "buenos aires": "America/Argentina/Buenos_Aires",
        "cape town": "Africa/Johannesburg",
        "nairobi": "Africa/Nairobi",
        "cairo": "Africa/Cairo",
        "mumbai": "Asia/Kolkata",
        "bangkok": "Asia/Bangkok",
        "singapore": "Asia/Singapore",
        "hong kong": "Asia/Hong_Kong",
        "seoul": "Asia/Seoul",
        "istanbul": "Europe/Istanbul",
        "madrid": "Europe/Madrid",
        "rome": "Europe/Rome",
        "athens": "Europe/Athens",
        "vienna": "Europe/Vienna",
        "zurich": "Europe/Zurich",
        "stockholm": "Europe/Stockholm",
        "oslo": "Europe/Oslo",
        "helsinki": "Europe/Helsinki",
        "copenhagen": "Europe/Copenhagen",
        "amsterdam": "Europe/Amsterdam",
        "brussels": "Europe/Brussels",
        "lisbon": "Europe/Lisbon",
        "warsaw": "Europe/Warsaw",
        "budapest": "Europe/Budapest",
        "prague": "Europe/Prague",
        "bucharest": "Europe/Bucharest",
        "sofia": "Europe/Sofia",
        "belgrade": "Europe/Belgrade",
        "zagreb": "Europe/Zagreb",
        "ljubljana": "Europe/Ljubljana",
        "sarajevo": "Europe/Sarajevo",
        "skopje": "Europe/Skopje",
        "tirana": "Europe/Tirane",
        "podgorica": "Europe/Podgorica",
        "reykjavik": "Atlantic/Reykjavik",
        "dublin": "Europe/Dublin",
        "edinburgh": "Europe/London",
        "cardiff": "Europe/London",
        "belfast": "Europe/London",
        "manila": "Asia/Manila",
        "kuala lumpur": "Asia/Kuala_Lumpur",
        "hanoi": "Asia/Ho_Chi_Minh",
        "phnom penh": "Asia/Phnom_Penh",
        "vientiane": "Asia/Vientiane",
        "yangon": "Asia/Yangon",
        "colombo": "Asia/Colombo",
        "male": "Indian/Maldives",
        "kathmandu": "Asia/Kathmandu",
        "thimphu": "Asia/Thimphu",
        "dhaka": "Asia/Dhaka",
        "islamabad": "Asia/Karachi",
        "tehran": "Asia/Tehran",
        "baghdad": "Asia/Baghdad",
        "riyadh": "Asia/Riyadh",
        "kuwait city": "Asia/Kuwait",
        "doha": "Asia/Qatar",
        "manama": "Asia/Bahrain",
        "muscat": "Asia/Muscat",
        "beirut": "Asia/Beirut",
        "damascus": "Asia/Damascus",
        "amman": "Asia/Amman",
        "jerusalem": "Asia/Jerusalem",
        "gaza": "Asia/Gaza",
        "ramallah": "Asia/Hebron",
        "sanaa": "Asia/Aden",
        "addis ababa": "Africa/Addis_Ababa",
        "khartoum": "Africa/Khartoum",
        "kampala": "Africa/Kampala",
        "kinshasa": "Africa/Kinshasa",
        "lagos": "Africa/Lagos",
        "accra": "Africa/Accra",
        "dakar": "Africa/Dakar",
        "casablanca": "Africa/Casablanca",
        "algiers": "Africa/Algiers",
        "tunis": "Africa/Tunis",
        "tripoli": "Africa/Tripoli",
        "rabat": "Africa/Casablanca",
        "lusaka": "Africa/Lusaka",
        "harare": "Africa/Harare",
        "maputo": "Africa/Maputo",
        "gaborone": "Africa/Gaborone",
        "windhoek": "Africa/Windhoek",
        "antananarivo": "Indian/Antananarivo",
        "port louis": "Indian/Mauritius",
        "victoria": "Indian/Mahe",
        "moroni": "Indian/Comoro",
        "mogadishu": "Africa/Mogadishu",
        "djibouti": "Africa/Djibouti",
        "asmara": "Africa/Asmara",
        "juba": "Africa/Juba",
        "bangui": "Africa/Bangui",
        "brazzaville": "Africa/Brazzaville",
        "libreville": "Africa/Libreville",
        "malabo": "Africa/Malabo",
        "yaounde": "Africa/Douala",
        "abidjan": "Africa/Abidjan",
        "ouagadougou": "Africa/Ouagadougou",
        "bamako": "Africa/Bamako",
        "niamey": "Africa/Niamey",
        "nouakchott": "Africa/Nouakchott",
        "bissau": "Africa/Bissau",
        "freetown": "Africa/Freetown",
        "monrovia": "Africa/Monrovia",
        "conakry": "Africa/Conakry",
        "lome": "Africa/Lome",
        "porto-novo": "Africa/Porto-Novo",
        "cotonou": "Africa/Porto-Novo",
        "sao tome": "Africa/Sao_Tome",
        "praia": "Atlantic/Cape_Verde",
        "nuuk": "America/Godthab",
        "thule": "America/Thule",
        "stanley": "Atlantic/Stanley",
        "puerto williams": "America/Punta_Arenas",
        "ushuaia": "America/Argentina/Ushuaia",
        "port-aux-francais": "Indian/Kerguelen",
        "noumea": "Pacific/Noumea",
        "port vila": "Pacific/Efate",
        "honolulu": "Pacific/Honolulu",
        "pago pago": "Pacific/Pago_Pago",
        "apia": "Pacific/Apia",
        "nuku'alofa": "Pacific/Tongatapu",
        "funafuti": "Pacific/Funafuti",
        "majuro": "Pacific/Majuro",
        "palikir": "Pacific/Pohnpei",
        "yaren": "Pacific/Nauru",
        "tarawa": "Pacific/Tarawa",
        "hagatna": "Pacific/Guam",
        "saipan": "Pacific/Saipan",
        "palau": "Pacific/Palau",
        "port moresby": "Pacific/Port_Moresby",
        "honiara": "Pacific/Guadalcanal",
        "suva": "Pacific/Fiji",
        "nadi": "Pacific/Fiji",
        "mata-utu": "Pacific/Wallis",
        "papeete": "Pacific/Tahiti",
        "rarotonga": "Pacific/Rarotonga",
        "aitutaki": "Pacific/Rarotonga",
        "alofi": "Pacific/Niue",
        "fakaofo": "Pacific/Fakaofo"
    }
    return regions.get(region, "Unknown Region")